export class Person {
    constructor(public age: Number,
        public classOfWorker: String,
        public industryCode: String,
        public OccupationCode: String,
        public education: String,
        public wagePerHour: String,
        public lastEducation: String,
        public maritalStatus: String,
        public majorindustry: String,
        public majorOccupationCode: String,
        public mace: String,
        public hispanice: String,
        public sex: String,
        public MemberOfLabor: String,
        public reasonForEnemployment: String,
        public fulltime: String,
        public capitalGain: String,
        public capitalLoss: String,
        public dividends: String,
        public incomeTaxLiability: String,
        public previousResidenceRegion: String,
        public householdWithFamily: String,
        public householdSimple: String,
        public weight: String,
        public msaChange: String,
        public regChange: String,
        public withinRegChange: String,
        public livedHere: String,
        public migrationPrevResInSunbelt: String,
        public numPersonsWorkedForEmployer: String,
        public familyMembersUnder118: String,
        public fatherBirthCountry: String,
        public motherBirthCountry: String,
        public birthCountry: String,
        public citizenship: String,
        public ownBusinessOrSelfEmployed: String,
        public fillQuestionnaireForVeteransAdmin: String,
        public veteransBenefits: String,
        public weeksWorkedInYear: String,
        public year: String,
        public salaryRange: String
        ) {
    }
  }
